language: objective-c
osx_image: xcode7.1
env:
  matrix:
    - PLATFORM=iOS SDK=iphonesimulator
    - PLATFORM=Mac SDK=macosx
before_script:
  - set -o pipefail
script:
  - cd "Example/$PLATFORM"
  - pod install
  - xcodebuild -workspace Example.xcworkspace -scheme Example -sdk $SDK
